services:
  backend:
    build: .
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      - MAILPIT_HOST=mailpit

    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"