spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

mail.from-address=${MAIL_FROM_ADDRESS}
