spring.mail.host=${MAILPIT_HOST:localhost}
spring.mail.port=${MAILPIT_PORT:1025}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

mail.from-address=${MAIL_FROM_ADDRESS:no-reply@ademy.local}
